package exceptionstudy;

public class Test {
	
	public void call() {
		System.out.println("실행 완료.");
	}

}
